Account for not providing environment on non-JSC machine
HPSCTerrSys/TSMP2 pull request #47
Opened 2024-12-06 09:09 UTC by mvhulten

This accounts for the complete truth table of (is var set?) and (are we on JSC?).  If neither is the case, the scripts aborts.

Furthermore, the abort message format is made consistent with another abort location (where I did not add a suggestion as providing model component parameters is already in the README).

Finally, I made messages for "things about to be done" contrast to aborts by making them present continuous tense and adding an ellipsis.

2024-12-06 13:32 UTC, kvrigor requested changes

2024-12-06 13:32 UTC, kvrigor commented on build_tsmp2.sh
> +  exit 1
ABORT is not necessary since we'd like `build_tsmp2.sh` to also work on non-JSC machines. `build_tsmp2.sh` works on my local Ubuntu machine which doesn't require `source`-ing an environment file.

2024-12-06 14:27 UTC, mvhulten commented on build_tsmp2.sh
> +  exit 1
I see!  I am reverting that...

However, it breaks in line 216 where realpath(1) expects a filename as argument.

Assuming we want absolute path names, I'll move it down to the next `if` block, Ok?

2024-12-09 08:48 UTC, mvhulten commented on build_tsmp2.sh
> +  exit 1
So, things *are* addressed, but GitHub is still saying
> Merging is blocked
> Merging can be performed automatically once the requested changes are addressed.

I will unresolve the issue s.t. @kvrigor can resolve it; maybe that will trigger automatic merge??

2024-12-09 08:54 UTC, mvhulten commented on build_tsmp2.sh
> +  exit 1
Request [has been addressed](d435a38ab69f61f7b93abe77746b32fd5a7f489e).

2024-12-09 09:03 UTC, mvhulten commented on build_tsmp2.sh
> +  exit 1
Since that commit reverts a change, please squash commits.

2024-12-09 15:38 UTC, mvhulten commented on build_tsmp2.sh
> +  exit 1
I think it does capture *Case 2*.  The second `if` block tests if `$tsmp2_env` is non-empty and *only then* sources the file…

Oh wait, *even if `tsmp2_env` is set*, you don't want to source it?
I don't get that: if a user uses the `--tsmp2_env` flag, I would think it would certainly want to source an environment‽

2024-12-10 07:44 UTC, kvrigor commented on build_tsmp2.sh
> +  exit 1
> The second if block tests if $tsmp2_env is non-empty and only then sources the file

You're right Marco; my bad. Also I just ran `./build_tsmp2.sh --eCLM` on my local machine and confirmed that it works. 

I'm approving the review now. I'll leave the merging to you so you have the freedom to write the commit message.

2024-12-10 07:45 UTC, kvrigor approved these changes

2024-12-10 08:54 UTC, merged